output_limit: use add_library instead of px4_add_library
px4_add_library adds uorb dependencies, which since 9b109a08af6 added libm.
This in turn led to build failures for px4_io-v2 in the form of:
__aeabi_f2d' wf_sqrt.c:(.text.sqrtf+0x54): undefined reference to
__aeabi_ddiv'