Multiple unaligned type cast
Multiple unaligned type cast.
Fix by one byte check here.
Firmware/src/lib/parameters/flashparams/flashfs.c:190:2: error: converting a packed 'flash_entry_header_t' {aka 'struct flash_entry_header_t'} pointer (alignment 1) to a 'uint32_t' {aka 'unsigned int'} pointer (alignment 4) may result in an unaligned pointer value [-Werror=address-of-packed-member]
  190 |  uint32_t *pm = (uint32_t *) pf;
      |  ^~~~~~~~
compilation terminated due to -Wfatal-errors.
cc1: all warnings being treated as errors

To be fixed...
Firmware/src/lib/parameters/flashparams/flashfs.c:480:5: error: converting a packed 'flash_entry_header_t' {aka 'struct flash_entry_header_t'} pointer (alignment 1) to a 'h_magic_t' {aka 'unsigned int'} pointer (alignment 4) may result in an unaligned pointer value [-Werror=address-of-packed-member]
  480 |     pmagic = (h_magic_t *) pf;
      |     ^~~~~~
compilation terminated due to -Wfatal-errors.
cc1: all warnings being treated as errors