Revert "uavcan: fixed build for MAVLink2"
This reverts commit fcaad2912cbc1d7224f0bef99fddf5998f405911.

It needs other changes in order to work. Currently breaks the build
with:
/home/lucas/p/dronecode/ardupilot/modules/PX4Firmware/src/modules/uavcan/uavcan_servers.cpp:65:33: fatal error: v2.0/common/mavlink.h: No such file or directory
 #include <v2.0/common/mavlink.h>
                                 ^